### ISSUE TITLE
Sherry 7/8/2019

### ISSUE THREAD

**Issue by benniezhu** [gliedgroup/ComparativeMortality#1]
Make a graph similar to the ones we have previously made in excel for each country? And or make a new type of graph

make australia the left out country and put in dummies for countries; eg i.country is there

do the triple interaction thing only for the US. eg. US dummy*agecat dummy* year decade dummy

**Comment by benniezhu** [comment]
Check output folder in comparative mortality for the model coefficients and a graph; specifically the file USDummyModelTripleInteraction.xlsx

**Comment by sherryg1** [comment]
Still not the right order for the graphs.  I want to see all the ages for each decade next to each other -- as shown on that slip of paper.  So for 1970, pattern of coefficients for 10-19, 20-29, 30-39, etc.  Then for 1980 etc.

**Comment by benniezhu** [comment]
I just updated it. Is the graph titled coefficients by year decade more or less what you were looking for?
